package:
  name: ecoscope-workflows-ext-gcf
  version: "0.1.1"

source:
  path: ..

build:
  noarch: python
  script: pip install --no-deps --no-build-isolation .

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - geopandas
    - pandas
    - pydantic
    - wt-registry >=0.2.0,<0.3.0

about:
  summary: GCF-specific custom tasks for Ecoscope Desktop workflows
  license: MIT
